##
## EPITECH PROJECT, 2019
## CPool_Day12_2019
## File description:
## makefile for cat
##

NAME	=	cat

SRC	=	cat/cat.c

CC	=	gcc

OBJ	=	$(SRC:.c=.o)

all	:	$(NAME)

$(NAME)	:	$(OBJ)
		$(CC) -o $(NAME) $(OBJ)
